config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  patch "sessions" => "sessions#create"

  resources :votes, only: [:new, :create, :index]
  patch "votes" => "votes#create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "sessions#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/candidate.rb
require "text"

class Candidate < ApplicationRecord
  validate :not_more_than_ten
  validates :name, presence: true

  # This is a custom validation that checks if there are already 10 candidates
  def not_more_than_ten
    if Candidate.count == 10
      errors.add(:candidate, "can only have 10 total candidates")
    end
  end

  # This checks for similar candidates and returns the closest match
  # If there is no close match, it creates a new candidate
  def self.add_new_candidate(candidate_name)
    closest = closest_match(candidate_name)
    if closest.present?
      closest.vote_count += 1
      closest.save
      return closest
    end
    Candidate.create(name: candidate_name, vote_count: 1)
  end

  # This uses the Levenshtein distance algorithm to check for similar candidates
  # There are likely better ways to do this, but this was the simplest option in the time limit.
  # https://en.wikipedia.org/wiki/Levenshtein_distance
  def self.closest_match(candidate_name)
    return nil if candidate_name.blank?
    Candidate.all.each do |candidate|
      # Did a bit of testing and 7 seems to be a good threshold for a match
      if Text::Levenshtein.distance(candidate_name, candidate.name) < 5
        return candidate
      end
    end
    nil
  end
end

app/models/voter.rb
class Voter < ApplicationRecord
  # validates both presence and format of email and zip code
  validates :email, presence: true
  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}
  validates :zip_code, presence: true
  validates_format_of :zip_code, with: /\A\d{5}-\d{4}|\A\d{5}\z/, message: "should be in the form 12345 or 12345-1234"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  # Logs out voter by deleting the encrypted voter_id cookie and setting the current_user to nil
  def logout_voter
    @current_user = nil
    cookies.encrypted[:voter_id] = nil
    cookies[:start_time] = nil
  end

  # Returns the current logged-in user
  def current_user
    @current_user ||= if cookies.encrypted[:voter_id]
      voter = Voter.find_by(id: cookies.encrypted[:voter_id])
      if voter
        voter
      else
        cookies.encrypted[:voter_id] = nil
        cookies[:start_time] = nil
        nil
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # GET /sessions/new
  # Logs out user any time they visit the login page
  def new
    logout_voter if current_user
    @voter = Voter.new
  end

  # POST/PATCH /sessions
  # Checks if voter exists and has not voted yet
  # If so, logs them in and redirects them to the voting page
  # If not, redirects them to the voting page with a message
  # If voter does not exist, creates a new voter and logs them in
  def create
    @voter = Voter.find_by(email: voter_params[:email])
    if @voter && !@voter.voted_at
      login_voter
    elsif @voter
      logout_voter
      redirect_to votes_path, notice: "You have already voted!"
    else
      @voter = Voter.new(voter_params)
      if @voter.save
        login_voter
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  # DELETE /sessions/1
  # logs out voter
  def destroy
    logout_voter
    redirect_to votes_path
  end

  private

  # Logs in voter by setting the encrypted voter_id cookie and setting the signed_in_at time
  def login_voter
    # signed_in_at ended up not really being used
    @voter.update(signed_in_at: Time.now)
    cookies.encrypted[:voter_id] = @voter.id
    cookies[:start_time] = Time.now.strftime("%d %b %Y %H:%M:%S %Z")
    redirect_to new_vote_path
  end

  # Only allow a list of trusted parameters through.
  def voter_params
    params.require(:voter).permit(:email, :zip_code)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  # GET /votes
  # Lists all candidates and vote counts
  def index
    @candidates = Candidate.all
  end

  # GET /votes/new
  # because the timer redirects if there's not a current user,
  # this can only be accessed by a voter who hasn't exceeded the time limit
  def new
    @candidate = Candidate.new
  end

  # POST/PATCH /votes
  # If the voter is voting for an existing candidate, increments the vote count
  # If the voter is voting for a new candidate, checks for similarities against existing candidates
  # or creates a new candidate if none is found (see models/candidate.rb)
  def create
    if params[:vote_for]
      @candidate = Candidate.find(params[:vote_for])
      @candidate.vote_count += 1
      @candidate.save
    else
      @candidate = Candidate.add_new_candidate(params[:candidate][:name])
    end

    if @candidate.errors.any?
      render :new, status: :unprocessable_entity
    else
      current_user.update(voted_at: Time.now)
      logout_voter
      redirect_to votes_path, notice: "Vote was successfully cast!"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>VOTE.WEBSITE</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <header>
      <h3>VOTE.WEBSITE</h3>
      <% if current_user %>
        <p>Signed in as <%= current_user.email %></p>
      <% elsif request.path == new_session_path %>
        <p><%= link_to "Results", votes_path %></p>
      <% else %>
        <p><%= link_to "Register", new_session_path %></p>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/votes/_candidate.html.erb
<div id="<%= dom_id candidate %>" class="vote_tally" role="vote tally">
  <p class="candidate_name">
    <%= candidate.name %>
  </p>

  <p class="candidate_vote_count">
    <%= candidate.vote_count %>
  </p>

</div>

app/views/votes/_form.html.erb
<%= form_with(model: candidate, url: votes_path, id: "new_candidate") do |form| %>
  <% if candidate.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
        <% candidate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, placeholder: "Enter name..." %>&nbsp;
    <%= form.submit "Vote", id: "vote_for_new_candidate" %>
  </div>
<% end %>

app/views/votes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Election Results</h1>

<div id="candidates" role="list of candidates">
  <% @candidates.each do |candidate| %>
    <%= render "votes/candidate", candidate: candidate %>
  <% end %>
</div>

app/views/votes/new.html.erb
<div class="timer">
  <span class="minute"></span><span class="second"></span>
</div>
<h1>Cast your vote today!</h1>
<%= form_tag(votes_path, id: "existing_candidate") do %>
  <% Candidate.all.each do |candidate| %>
    <div>
      <%= radio_button_tag :vote_for, candidate.id %>
      <%= label_tag(:vote_for, candidate.name) %>
    </div>
    <br>
  <% end %>
  <%= submit_tag "Vote", id: "vote_for_existing_candidate" %>
<% end %>
<br>
<% if Candidate.count < 10 %>
   <hr>
   <br>
   <h3> Or, add a new candidate:</h3>
   <%= render "form", candidate: @candidate %>
   <br>
<% end %>